# Generated by Django 3.1.5 on 2021-04-17 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('tuber_id', models.IntegerField(blank=True)),
                ('user_id', models.IntegerField(blank=True)),
                ('email', models.CharField(max_length=255)),
                ('tuber_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=255)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
