# Generated by Django 3.1.5 on 2021-04-18 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='address',
        ),
        migrations.AddField(
            model_name='info',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='country',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='state',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='street',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
