# Generated by Django 3.1.5 on 2021-04-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_auto_20210418_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='heading',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
