# Generated by Django 3.1.5 on 2021-04-19 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_remove_info_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='heading',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
