# Generated by Django 3.1.5 on 2021-04-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_info_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='heading',
        ),
    ]
