# Generated by Django 3.1.5 on 2021-04-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_remove_info_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='heading',
            field=models.CharField(default='Company details', max_length=255),
        ),
    ]
