# Generated by Django 3.1.5 on 2021-04-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0011_about_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about_detail',
        ),
    ]
