# Generated by Django 3.1.5 on 2021-04-19 08:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0012_delete_about_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/about')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
