# Generated by Django 3.1.5 on 2021-01-29 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ytuber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='media/youtubers/%Y/%m')),
                ('age', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('video_url', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('crew', models.CharField(max_length=255)),
                ('camera_type', models.CharField(max_length=255)),
                ('subs_count', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 1, 29, 15, 25, 17, 453935))),
            ],
        ),
    ]
