# Generated by Django 3.1.5 on 2021-04-18 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0005_auto_20210418_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytuber',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 13, 6, 45, 346805)),
        ),
    ]
